### ISSUE TITLE
Add a CONTRIBUTING.MD file

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [redteam-project/sckg#5]
Add guidelines to communicate how people should contribute to project. 

Reference: [Setting guidelines for repository contributors](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)

**Comment by jason-callaway** [comment]
Resolved by 5404204

Thanks for being awesome, @its-a-lisa! Keep em coming!
